### ISSUE TITLE
Navigation Menu is not visible

### ISSUE THREAD

**Issue by Davisy** [pycontanzania/pycon.or.tz#14]
The navigation menu is not visible when accessing the website on a smartphone or in mobile view.I just show the logo and the button to buy ticket.

**Comment by mtuchi** [comment]
> The navigation menu is not visible when accessing the website on a smartphone or in mobile view.I just show the logo and the button to buy ticket.

Add a screenshot @Davisy

**Comment by Davisy** [comment]
> > The navigation menu is not visible when accessing the website on a smartphone or in mobile view.I just show the logo and the button to buy ticket.
> 
> Add a screenshot @Davisy

<img width="427" alt="Screenshot 2021-12-02 at 16 33 42" src="https://user-images.githubusercontent.com/20296550/144485341-06a909b1-ba7c-4988-b7ce-e5d796e38a17.png">
