### ISSUE TITLE
Add reports on the website

### ISSUE THREAD

**Issue by mtuchi** [pycontanzania/pycon.or.tz#18]
## Description
A page for all Pycon Tanzania reports, that show our expenses, our planning,  the impact we had etc

**Comment by decolnz** [comment]
Hi Mtuchi

Please kindly upload the following report to the website. 

[PyCon Report 2021.pdf](https://github.com/pycontanzania/pycon.or.tz/files/9242840/PyCon.Report.2021.pdf)
